name = "CoolWalksUtils"
uuid = "5abba2a6-77e2-4331-9785-93f3fa89e9c9"
authors = ["Henrik Wolf <henrik-wolf@freenet.de> and contributors"]
version = "0.1.0"

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
ArchGDAL = "0.9"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
